###
GET http://localhost:8080/prj_assignment_war_exploded/ProductServlet?page=2&limit=3&sortName=price&sortBy=desc

###
POST http://localhost:8080/prj_assignment_war_exploded/ProductServlet
Content-Type: application/json

{
  "name": "La roche lotion",
  "price": "25",
  "quantity": "30",
  "description": "Rose water toner and lotion",
  "categoryId": "3",
  "sellerId": "3",
  "image_url": "http//image-link.png"
}

###
GET http://localhost:8080/prj_assignment_war_exploded/OrderServlet
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhdXRoMCIsInVzZXIiOnsiaWQiOjIsInVzZXJuYW1lIjoiZG9hbmh0aHVjIn19.jVBluCV8pYbdpyc8GivIjjKPU9kOVsTBvjLFo7WoJSM

###
POST http://localhost:8080/prj_assignment_war_exploded/OrderServlet
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhdXRoMCIsInVzZXIiOnsiaWQiOjIsInVzZXJuYW1lIjoiZG9hbmh0aHVjIn19.jVBluCV8pYbdpyc8GivIjjKPU9kOVsTBvjLFo7WoJSM
Content-Type: application/json

{
  "customerId": "2",
  "orderList": [
    {
      "id": "2",
      "name": "Samsung galaxy note 21",
      "quantity": "1",
      "price": "110"
    }
  ]
}

###
POST http://localhost:8080/prj_assignment_war_exploded/LoginServlet
Content-Type: application/json

{
  "username": "doanhthuc",
  "password": "123"
}

###
POST http://localhost:8080/prj_assignment_war_exploded/RegisterServlet
Content-Type: application/json

{
  "fullName": "Nguyen Van Tien Dung",
  "username": "tiendungAI",
  "password": "tiensiML",
  "address": "vien AI Nha Trang",
  "phone": "0339198650",
  "roleId": "2"
}